
name: "Continuous Integration"

on:
  pull_request: null

jobs:
  phpunit:
    name: "PHPUnit"
    uses: "doctrine/.github/.github/workflows/contiuous-integration.yml@1.2.0"
    with:
      composer-root-version: "2.2"
      php-versions: '["7.1", "7.2", "7.3", "7.4", "8.0"]'
